version: '2'

services:
    mysql:
        build:
            context: ./dockerfiles/mysql
        ports:
            - "3306:3306"
    redis:
        build:
            context: ./dockerfiles/redis
        ports:
            - "6379:6379"
